# .air.toml

# プロジェクトのルートディレクトリ
root = "."

# [build] セクション: ビルド方法の定義
[build]
  # 変更を検知した時に実行するコマンド
  # 1. go mod tidy: 新しいライブラリのimportに対応
  # 2. go build: /app/main という名前でビルド
  cmd = "go mod tidy && go build -o /app/main ./cmd/server"
  
  # ビルド後に実行するバイナリファイル
  bin = "/app/main"

# [watch] セクション: 監視対象の定義
[watch]
  # 監視するファイルの拡張子
  include_ext = ["go", "toml", "mod"]
  
  # 監視から除外するディレクトリ
  exclude_dir = ["vendor", "tmp", "bin"]